# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DC Pair Programming
email: >
description: Rubyists in the DC-area pairing together online, working to develop code in a TDD, agile, manner.
baseurl: "" # the subpath of your site, e.g. /blog
url: "dc-pair-programming.github.io" # the base hostname & protocol for your site
twitter_username: >
github_username:  DC-Pair-Programming

# Build settings
markdown: kramdown
